// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPHapQ5oFdQ_tfYURsLPBzpbiWZHow0Ng',
    appId: '1:189683718591:web:1195a8d42078fd4e26e90a',
    messagingSenderId: '189683718591',
    projectId: 'athlete-app-e1740',
    authDomain: 'athlete-app-e1740.firebaseapp.com',
    storageBucket: 'athlete-app-e1740.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCOyD_Hd9srYGf8wDTfWZmEb4l3UZ7BC4',
    appId: '1:189683718591:android:cc8cf5a88bf12ee226e90a',
    messagingSenderId: '189683718591',
    projectId: 'athlete-app-e1740',
    storageBucket: 'athlete-app-e1740.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQhDmkD4Nupxvrs4GMiTBI0dj7i-luyBk',
    appId: '1:189683718591:ios:a5b25f7e0d5a483b26e90a',
    messagingSenderId: '189683718591',
    projectId: 'athlete-app-e1740',
    storageBucket: 'athlete-app-e1740.firebasestorage.app',
    iosBundleId: 'com.example.athleteiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQhDmkD4Nupxvrs4GMiTBI0dj7i-luyBk',
    appId: '1:189683718591:ios:a5b25f7e0d5a483b26e90a',
    messagingSenderId: '189683718591',
    projectId: 'athlete-app-e1740',
    storageBucket: 'athlete-app-e1740.firebasestorage.app',
    iosBundleId: 'com.example.athleteiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPHapQ5oFdQ_tfYURsLPBzpbiWZHow0Ng',
    appId: '1:189683718591:web:63f1ba613b9610f526e90a',
    messagingSenderId: '189683718591',
    projectId: 'athlete-app-e1740',
    authDomain: 'athlete-app-e1740.firebaseapp.com',
    storageBucket: 'athlete-app-e1740.firebasestorage.app',
  );
}
